# Generated by Django 2.2.5 on 2021-11-06 18:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20211105_2027'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='langauae',
            new_name='language',
        ),
    ]
